version: '3.7'

services:
  app:
    build:
      context: app
    ports:
      - "9980:80"
      - "9981:80"
      - "9982:80"
      - "9983:80"
      - "9984:80"
      - "9985:80"
      - "9986:80"
      - "9987:80"
      - "9988:80"
      - "9989:80"

  gateway:
    build:
      context: gateway
    environment:
      WHITELIST_REGEX: "^http:\\/\\/localhost(:\\d+)?" # TODO Change to actual one
    ports:
      - "9999:80"

  # Called this way to be linked correctly by app
  dex:
    image: dexidp/dex:v2.37.0-alpine
    command: ["dex", "serve", "/etc/config.yaml"]
    volumes:
      - ./dex/config.yml:/etc/config.yaml:ro
    environment:
      GITHUB_CLIENT_ID: # TODO Change to the expected one
      GITHUB_CLIENT_SECRET: # TODO Change to the expected one
    ports:
      - "5556:5556"
